# Generated by Django 6.1 on 2026-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='item',
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='skills', to='main.tag'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
