# Generated by Django 6.1 on 2026-09-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_skill_item_skill_tag_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='tag',
            new_name='tags',
        ),
    ]
