# Generated by Django 6.1 on 2026-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_convert_existing_tag_ids_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
